spring.application.name=order-management-api
spring.jpa.open-in-view=false
# SpringDoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
# JWT
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration-minutes=${JWT_EXPIRATION:30}