# DATASOURCE
spring.datasource.driver-class-name=org.h2.Driver
# Use H2 in PostgreSQL compatibility mode so Flyway Postgres SQL works better in tests
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
# Enable Flyway for test profile and let Flyway manage schema. Disable Hibernate auto DDL.
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none